### ISSUE TITLE
not taking param into consideration?

### ISSUE THREAD

**Issue by shez1983** [GeneaLabs/laravel-model-caching#67] opened 2018-02-12 11:13 UTC
So I have a query such as this. and i have an api endpoint categories/id/products..

```
$collection = ProductVariant::with( 'product.owner' )->whereHas( 'product', function( $q ) use ( $categoryId )
            {
                $q->whereCategoryId($categoryId)->live();
            } )->inRandomOrder()->live(1)
```
but when i change the id to say 2 or 3.. I get same products.. is this something I have to take care of? or am i doing something wrong?

## Environment
Laravel Version: *5.6.2*
Laravel Model Caching Package Version: *^0.2.22*
PHP Version: * 7.1.6 *
Homestead Version: *N/A* (using Valet)
Operating System & Version: *Mac OS - El captain - 10.11.6 *

**Comment by mikebronner** [comment] 2018-02-12 14:41
Thanks for reporting this @shez1983 ! I'll take a look as soon as I get back to the office on Tuesday.

**Comment by shez1983** [comment] 2018-02-12 15:08
i'll make sure I update this post before tuesday.. Thanks :)

**Comment by mikebronner** [comment] 2018-02-13 16:37
Related or same as #66

**Comment by mikebronner** [comment] 2018-02-14 00:43
@shez1983 Are `inRandomOrder()` and `live()` query scopes? Can you paste them here as well? Thanks! :)

**Comment by shez1983** [comment] 2018-02-19 11:30
I am sorry for the delay... :( 

```
"select * from `product_variants` where exists (select * from `products` where `product_variants`.`product_id` = `products`.`id` and `category_id` = ? and `status_id` = ? and `show_on_mobile` = ?) and `is_listed` = ? and (`stock` is null or `stock` > ?) and `product_variants`.`deleted_at` is null order by RAND()"
```

Here is the live Scope
```  public function scopeLive($q)
    {
        return $q->whereIsListed(1)->where(function($q)
        {
           return $q->whereNull('stock')->orWhere('stock', '>', 0);
        });
    }
```

inRandomOrder is an ELOQUENT/Builder function btw..

I am not sure how to include a stack trace because theres no error..

**Comment by mikebronner** [comment] 2018-02-19 13:59
@shez1983 thanks for the update. In your eloquent query you aren't specifying `get()`? Was that just a typo, or are you using a different command?

**Comment by shez1983** [comment] 2018-02-20 15:18
yes. as i said i can see the actual products.. if i didnt specify get() i wouldnt have come to the conclusion of my OP.. :)

**Comment by mikebronner** [comment] 2018-02-24 16:15
Hi @shez1983, I am unable to reproduce this problem in version 0.2.37. Can you test again? I have added a test that checks the caching for the `whereHas()` method. Please let me know how it goes! :)

**Comment by mikebronner** [comment] 2018-03-01 00:24
@shez1983  closing this for now, please let me know if you continue to have this problem.

**Comment by shez1983** [comment] 2018-03-01 22:17
oops sorry - too busy with work will let you know sometime.

**Comment by mikebronner** [comment] 2018-03-02 02:35
Try this:
https://github.com/GeneaLabs/laravel-model-caching/blob/master/tests/Integration/CachedModelTest.php#L77

**Comment by shez1983** [comment] 2018-03-04 00:19
Thanks for that - seeing your test, it seems you have not understood my problem...
that test is not recreating what i said in my op.. 

in that test i expected you to cache both 

```$books = (new Book)
            ->with('author')
            ->whereHas('author', function ($query) {
                $query->whereId(1);
            })
            ->get();```
and 
```$books = (new Book)
            ->with('author')
            ->whereHas('author', function ($query) {
                $query->whereId(2);
            })
            ->get();```

and then make sure the results are not the same..

**Comment by mikebronner** [comment] 2018-03-04 00:30
Thanks for clarifying, that indeed was not clear in your initial post. I will try to recreate the problem as you just described.

**Comment by mikebronner** [comment] 2018-03-04 00:41
@shez1983 I added the following test: https://github.com/GeneaLabs/laravel-model-caching/commit/d00302814dd5ce5e6b715cbd11f2544dc521b5c8

Does this follow your use-case? I was unable to replicate the issue.

**Comment by shez1983** [comment] 2018-03-04 00:58
+        $this->assertNotEmpty($books1->diffKeys($books2)); 
surely this should assertEMPTY if there can only be one author for a book? and you are not caching the results...

you are supposed to be looking at cached results (Unless i am missing something) not comparing eloquent/query results...

**Comment by mikebronner** [comment] 2018-03-04 01:04
Your original post was saying that running two different queries are note returning the correct information. Do I understand that correctly?

This test does use caching, and it verifies that the results from each cached query are different. That is to say, that the results provided in `$books2` are not the same as those in `$books1`. Since `whereHas` queries are cached, as verified in the test above this one, it is not necessary to verify that. We only need to make sure that the second query is not pulling the cache from the first query.

Have you actually been able to recreate this issue with the latest version of the package?

**Comment by shez1983** [comment] 2018-03-04 11:33
yes thats correct. in your previous test (link you provided:
https://github.com/GeneaLabs/laravel-model-caching/blob/master/tests/Integration/CachedModelTest.php#L77

 you were doing
``` 
$cachedResults = $this
            ->cache()
            ->tags($tags)
            ->get($key)['value'];
        $this->assertEquals(1, $books->first()->author->id);
        $this->assertEquals(1, $cachedResults->first()->author->id);
```

so i was expecting something similar in your latest test you did... d003028

anyway i will re-test (i actually tested it again few days after posting to make sure i didnt make an error) & let you know

**Comment by mikebronner** [comment] 2018-03-04 14:36
Thanks, I look forward to seeing how it works for you! :)

**Comment by mikebronner** [comment] 2018-03-10 04:32
HI @shez1983, closing this for now. If there are still issues, please go ahead and re-open. Thanks :)

**Closed by mikebronner** 2018-03-10 04:32 UTC
Labels: Unconfirmed Bug, follow-up required
