### ISSUE TITLE
Feature request: possibility of automatically chunking large collections

### ISSUE THREAD

**Issue by hyperized** [GeneaLabs/laravel-model-caching#101] opened 2018-03-14 13:24 UTC
# Issue
Thank you for making this library, it's helping us a lot!
We're dealing with larger datasets and this helps speeding up our system a lot.

We're currently trying to prefetch results so a cache-warm can be done prior to processing large datasets. However when we try to use model caching on large tables (300k+ entries) Redis hangs up due to the enormous size of the values of result keys.

The stack trace below shows what happens, but basically: Redis hangs up because the value entered is too large.

When we use smaller datasets (`Countries::all()`) we observe collections of models being cached in a single key, rather than individual models (which we kind of were expecting).

Since huge collections fail, we attempted to chunk them in order to force smaller cache value sets:
```
(new \App\Models\Flight)->chunk(10000, function($chunk) { /* do nothing */ });
```
But this results cache entry identifier to be based on the chunk alone, and when a cached item from the `Flight` model is requested, it actually ends up going back to the database anyway.

Now the feature request is: can these large datasets natively be chunked by the library somehow, or alternatively: can we prefetch with this library other than iterating over individual table entries?

Thank you got considering!

## Environment
Laravel Version: 5.6.11
Laravel Model Caching Package Version: 0.2.51
PHP Version: 7.1.7
Homestead Version: n/a
Operating System & Version: n/a

## Stack Trace
```
Flight::all();
```
will yield:

```
[Processing flight information]

[DB::listener output]
string(20) "select * from "flights""
array(0) {
}
float(5990.68)

[Error]
Predis\Connection\ConnectionException {#372159
  -connection: Predis\Connection\StreamConnection {#685
    -cachedId: null
    #parameters: Predis\Connection\Parameters {#683
      -parameters: array:5 [
        "host" => "127.0.0.1"
        "password" => {redacted}
        "port" => "6379"
        "database" => 0
        "scheme" => "tcp"
      ]
    }
    #initCommands: array:1 [
      0 => Predis\Command\RawCommand {#686
        -slot: null
        -commandID: "SELECT"
        -arguments: array:1 [
          0 => 0
        ]
      }
    ]
  }
  #message: "Error while writing bytes to the server. [tcp://127.0.0.1:6379]"
  #code: 0
  #file: "./vendor/predis/predis/src/Connection/AbstractConnection.php"
  #line: 155
  trace: {
    ./vendor/predis/predis/src/Connection/AbstractConnection.php:155 { …}
    ./vendor/predis/predis/src/Connection/StreamConnection.php:298 { …}
    ./vendor/predis/predis/src/Connection/StreamConnection.php:394 { …}
    ./vendor/predis/predis/src/Connection/AbstractConnection.php:110 { …}
    ./vendor/predis/predis/src/Client.php:331 { …}
    ./vendor/predis/predis/src/Client.php:314 { …}
    ./vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:96 { …}
    ./vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php:108 { …}
    ./vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php:165 { …}
    ./vendor/laravel/framework/src/Illuminate/Cache/Repository.php:303 { …}
    ./vendor/laravel/framework/src/Illuminate/Cache/RedisTaggedCache.php:46 { …}
    ./vendor/laravel/framework/src/Illuminate/Cache/Repository.php:362 { …}
    ./vendor/genealabs/laravel-model-caching/src/CachedBuilder.php:232 { …}
    ./vendor/genealabs/laravel-model-caching/src/CachedBuilder.php:177 { …}
    ./vendor/genealabs/laravel-model-caching/src/CachedBuilder.php:78 { …}
    ./vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:371 { …}
    ./vendor/genealabs/laravel-model-caching/src/Traits/ModelCaching.php:21 { …}
    ./vendor/laravel/framework/src/Illuminate/Cache/Repository.php:362 { …}
    ./vendor/genealabs/laravel-model-caching/src/Traits/ModelCaching.php:22 { …}
    ./app/Jobs/Flight/Process.php:131 {
      › Flight::all();
    }
    App\Jobs\Flight\Process->handle() {}
    ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/Container.php:564 { …}
    ./vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:94 { …}
    ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:114 { …}
    ./vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102 { …}
    ./vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php:98 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:49 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:83 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/Worker.php:322 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/Worker.php:272 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/Worker.php:229 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:101 { …}
    ./vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:85 { …}
    Illuminate\Queue\Console\WorkCommand->handle() {}
    ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31 { …}
    ./vendor/laravel/framework/src/Illuminate/Container/Container.php:564 { …}
    ./vendor/laravel/framework/src/Illuminate/Console/Command.php:183 { …}
    ./vendor/symfony/console/Command/Command.php:252 { …}
    ./vendor/laravel/framework/src/Illuminate/Console/Command.php:170 { …}
    ./vendor/symfony/console/Application.php:865 { …}
    ./vendor/symfony/console/Application.php:241 { …}
    ./vendor/symfony/console/Application.php:143 { …}
    ./vendor/laravel/framework/src/Illuminate/Console/Application.php:88 { …}
    ./vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:121 { …}
    ./artisan:37 { …}
  }
}
```

**Comment by mikebronner** [comment] 2018-03-14 14:33
Thanks for posting this detailed explanation of your use-case. The only way this could work is if I can figure out how to cache the chunked results, instead of the chunking instance. I will look into this some more over the next few days.

**Comment by hyperized** [comment] 2018-03-19 09:44
Hi @mikebronner, thanks for having a look. Is there anything we can do to help?

**Comment by mikebronner** [comment] 2018-03-19 11:09
Sorry it's taking a while, my computer was out of commission since Friday, but have it working again. Hope to get to this in the next day or two. :)

**Comment by mikebronner** [comment] 2018-03-24 17:24
Hi @hyperized, I'm thinking this needs to be addressed with the Redis configuration. Even if we cached the chunks, the total records would eventually get cached in Redis, and cause it to run out of memory. You should look at configuring your Redis installation for high-volume data, or perhaps not cache these huge queries. Chunked queries are actually being cached (I just confirmed this), so you might want to implement your query as a chunked query, instead of using `all()`. In the end the data management and implementation is up to you, I don't really want to alter a developer's query and chunk something, when they didn't ask for it. :) Good luck, feel free to update this issue as you work through sorting this out, but I will close it for now, as I won't be addressing this specific use-case in the package.

Here is an excellent resource on working with Redis, see lesson 9 perhaps:
https://scaleyourcode.com/blog/article/10

**Closed by mikebronner** 2018-03-24 17:24 UTC
Labels: enhancement
