### ISSUE TITLE
vsprintf(): Too few arguments

### ISSUE THREAD

**Issue by rajnishmishra20** [GeneaLabs/laravel-model-caching#296] opened 2019-10-12 08:44 UTC
**Describe the bug**
Exception occurs when using **eagerLoadRelation** on Model with **Cachable** trait. 

**Eloquent Query**
```php
$parents = Category::where('category_id', Category::encodeUuid($uuid))->with('word')->with('posts')->withCount('posts')->get();
```

**Stack Trace**
vsprintf(): Too few arguments

    protected function getInAndNotInClauses(array $where) : string
    {
        if (! in_array($where["type"], ["In", "NotIn", "InRaw"])) {
            return "";
        }
 
        $type = strtolower($where["type"]);
        $subquery = $this->getValuesFromWhere($where);
        $values = collect($this->query->bindings["where"][$this->currentBinding] ?? []);
        $this->currentBinding += count($where["values"]);
        $subquery = collect(**vsprintf**(str_replace("?", "%s", $subquery), $values->toArray()));
        $values = $this->recursiveImplode($subquery->toArray(), "_");
 
        return "-{$where["column"]}_{$type}{$values}";
    }

**Environment**
 - PHP: [ 7.3.0]
 - OS: [ Ubuntu 18.04]
 - Laravel: [e.g. 5.8.]
 - Model Caching: [ 0.7] (*)

Model uses \Ramsey\Uuid\Uuid for primary keys

**Comment by mikebronner** [comment] 2019-10-12 14:44
@rajnishmishra20 Thanks for reporting this. Could you provide the complete stack trace entry from `/storage/logs/laravel.log`? Thanks!

**Comment by rajnishmishra20** [comment] 2019-10-15 10:19
[2019-10-15 10:17:09] development.ERROR: vsprintf(): Too few arguments {"exception":"[object] (ErrorException(code: 0): vsprintf(): Too few arguments at /var/www/coloursappdev/vendor/genealabs/laravel-model-caching/src/CacheKey.php:232)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'vsprintf(): Too...', '/var/www/colour...', 232, Array)
#1 /var/www/coloursappdev/vendor/genealabs/laravel-model-caching/src/CacheKey.php(232): vsprintf('\\x8E\\x88.\\xDE\\x03\\xFCH\\x13\\x92\\xC7\\xB7\\xF9$\\x0F2...', Array)
#2 /var/www/coloursappdev/vendor/genealabs/laravel-model-caching/src/CacheKey.php(197): GeneaLabs\\LaravelModelCaching\\CacheKey->getInAndNotInClauses(Array)
#3 [internal function]: GeneaLabs\\LaravelModelCaching\\CacheKey->GeneaLabs\\LaravelModelCaching\\{closure}(NULL, Array)
#4 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1512): array_reduce(Array, Object(Closure), NULL)
#5 /var/www/coloursappdev/vendor/genealabs/laravel-model-caching/src/CacheKey.php(201): Illuminate\\Support\\Collection->reduce(Object(Closure))
#6 /var/www/coloursappdev/vendor/genealabs/laravel-model-caching/src/CacheKey.php(40): GeneaLabs\\LaravelModelCaching\\CacheKey->getWhereClauses()
#7 /var/www/coloursappdev/vendor/genealabs/laravel-model-caching/src/Traits/Caching.php(161): GeneaLabs\\LaravelModelCaching\\CacheKey->make(Array, NULL, '')
#8 /var/www/coloursappdev/vendor/genealabs/laravel-model-caching/src/Traits/Buildable.php(95): GeneaLabs\\LaravelModelCaching\\CachedBuilder->makeCacheKey(Array)
#9 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(155): GeneaLabs\\LaravelModelCaching\\CachedBuilder->get(Array)
#10 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(144): Illuminate\\Database\\Eloquent\\Relations\\Relation->get()
#11 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(569): Illuminate\\Database\\Eloquent\\Relations\\Relation->getEager()
#12 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(538): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelation(Array, 'template', Object(Closure))
#13 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(506): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelations(Array)
#14 /var/www/coloursappdev/vendor/genealabs/laravel-model-caching/src/Traits/Buildable.php(290): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#15 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(418): GeneaLabs\\LaravelModelCaching\\CachedBuilder->GeneaLabs\\LaravelModelCaching\\Traits\\{closure}()
#16 /var/www/coloursappdev/vendor/genealabs/laravel-model-caching/src/Traits/Buildable.php(292): Illuminate\\Cache\\Repository->rememberForever('d94c2f3d80f6d4d...', Object(Closure))
#17 /var/www/coloursappdev/vendor/genealabs/laravel-model-caching/src/Traits/Buildable.php(227): GeneaLabs\\LaravelModelCaching\\CachedBuilder->retrieveCachedValue(Array, 'genealabs:larav...', Array, 'd94c2f3d80f6d4d...', 'get')
#18 /var/www/coloursappdev/vendor/genealabs/laravel-model-caching/src/Traits/Buildable.php(97): GeneaLabs\\LaravelModelCaching\\CachedBuilder->cachedValue(Array, 'genealabs:larav...')
#19 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(751): GeneaLabs\\LaravelModelCaching\\CachedBuilder->get(Array)
#20 /var/www/coloursappdev/vendor/genealabs/laravel-model-caching/src/Traits/Buildable.php(290): Illuminate\\Database\\Eloquent\\Builder->paginate(50)
#21 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(418): GeneaLabs\\LaravelModelCaching\\CachedBuilder->GeneaLabs\\LaravelModelCaching\\Traits\\{closure}()
#22 /var/www/coloursappdev/vendor/genealabs/laravel-model-caching/src/Traits/Buildable.php(292): Illuminate\\Cache\\Repository->rememberForever('0a64d8225af1544...', Object(Closure))
#23 /var/www/coloursappdev/vendor/genealabs/laravel-model-caching/src/Traits/Buildable.php(227): GeneaLabs\\LaravelModelCaching\\CachedBuilder->retrieveCachedValue(Array, 'genealabs:larav...', Array, '0a64d8225af1544...', 'paginate')
#24 /var/www/coloursappdev/vendor/genealabs/laravel-model-caching/src/Traits/Buildable.php(166): GeneaLabs\\LaravelModelCaching\\CachedBuilder->cachedValue(Array, 'genealabs:larav...')
#25 /var/www/coloursappdev/app/Http/Controllers/Content/Api/ApiTemplateController.php(57): GeneaLabs\\LaravelModelCaching\\CachedBuilder->paginate(50)
#26 [internal function]: App\\Http\\Controllers\\Content\\Api\\ApiTemplateController->all_templates('8e804536-d319-4...')
#27 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#28 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('all_templates', Array)
#29 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Content\\Api\\ApiTemplateController), 'all_templates')
#30 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#31 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#32 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#38 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#41 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#42 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#43 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#44 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#45 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/coloursappdev/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/www/coloursappdev/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /var/www/coloursappdev/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#65 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Clockwork\\Support\\Laravel\\ClockworkMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#68 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#69 /var/www/coloursappdev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#70 /var/www/html/coloursappdev/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#71 {main}
"}

**Comment by mikebronner** [comment] 2019-10-15 16:33
@rajnishmishra20 Are you able to reproduce this in a model that doesn't use UUID?
Also, can you provide me the string value of `Category::encodeUuid($uuid)`? Thanks. I am currently unable to replicate the issue using the following query:
```php
        $parents = (new Book)
            ->where('author_id', 1)
            ->with('stores')
            ->with('publisher')
            ->withCount('stores')
            ->get();
```

**Comment by rajnishmishra20** [comment] 2019-10-18 11:48
Hi I am  \Ramsey\Uuid\Uuid for primary keys

This is Category::decodeUuid($uuid) 8eae24c5cd3a484fb95259066fa9e83f

This is Category::encodeUuid($uuid)  b"Ž®$ÅÍ:HO¹RY\x06o©è?"

Hope this helps, I am stuck at this.

**Comment by mikebronner** [comment] 2019-10-18 14:10
@rajnishmishra20 Thanks, this helps. The problem is the question mark in the ID. I will see what I can do to work around this. Hopefully I will have an update ready sometime in the next few days.

**Comment by mikebronner** [comment] 2019-10-18 15:28
@rajnishmishra20 This should now be fixed in release 0.7.3. Could you let me know how that works for you? Thanks!

**Comment by rajnishmishra20** [comment] 2019-10-24 05:35
Its fine now. Thanks!

**Comment by rajnishmishra20** [comment] 2019-10-25 11:19
Hey Sorry to open this again but it did not work. I had MODEL_CACHE_ENABLED set to false


After enabling , same error occurs

```
    protected function getInAndNotInClauses(array $where) : string
    {
        if (! in_array($where["type"], ["In", "NotIn", "InRaw"])) {
            return "";
        }
 
        $type = strtolower($where["type"]);
        $subquery = $this->getValuesFromWhere($where);
        $values = collect($this->query->bindings["where"][$this->currentBinding] ?? []);
        $this->currentBinding += count($where["values"]);
        $subquery = preg_replace('/\?(?=(?:[^"]*"[^"]*")*[^"]*\Z)/m', "_??_", $subquery);
###       $subquery = collect(vsprintf(str_replace("_??_", "%s", $subquery), $values->toArray()));
        $values = $this->recursiveImplode($subquery->toArray(), "_");
 
        return "-{$where["column"]}_{$type}{$values}";
    }
```

**Comment by mikebronner** [comment] 2019-10-25 15:00
Hi @rajnishmishra20, could you provide the stacktrace again, as well as the category UUIDs that cause this error? Thanks!

**Comment by mikebronner** [comment] 2019-10-25 16:00
Just saw you added the example link, thanks for that.
Inspecting the queries that are being run, the following looks odd to me:
```sql
select * from `categories` where `categories`.`id` in ('????????????????') and `categories`.`deleted_at` is null and `categories`.`deleted_at` is null
```

**Comment by rajnishmishra20** [comment] 2019-10-27 07:27
Hi may be, I found the root of problem. when ever I try to egarload a relation with another elager loaded relation all having a binary id th problem occurs.

Ex if from Category::with('word')->with('contents')->with('category')->doesntHave('category')->with('packs')->simplePaginate($pages);

Suppose ->with('packs') contains another relation on model definition  of relation the problem occurs
 public function packs()
    {
        return $this->hasMany(Category::class, 'category_id')->with('contents');
    }

if I remove ->with('contents') above it will work , else it will not.

**Comment by mikebronner** [comment] 2019-10-27 15:04
@rajnishmishra20 I need the values that are being passed in to work around the binary data.

**Comment by rajnishmishra20** [comment] 2019-10-31 07:27
Some example categories 

array:22 [▼
  0 => b"Ž€E6Ó\x19Jý°\x1Ak%‚®éí"
  1 => b"ÄÇEâ3ÎM¦ñ┌?╬³çÅC"
  2 => b"Ž€E¯{ÔJ›…\x03¨)L/òº"
  3 => b"Ž€Eç?ML%µ\x1EGUY\x128«"
  4 => b"Ž€F\x03\½JÚšbå.ª\x124ö"
  5 => b"Ž€F›Â…E\x03’ÇÄá]4Ÿ1"
  6 => b"Ž€F»JœEf˜\x1FYÌZ»óJ"
  7 => b"Ž€G›{CL%½¾\x07Â@Çû¤"
  8 => b"""
    ÄÇHVJ


    AÅÉïƒ ¶ÌÖj
    """
  9 => b"Ž€IS †I:ŽrÐ\x1Fç¤Û\x13"
  10 => b"Ž€K¹ë\eIc™ˆor6ÄIK"
  11 => b"Ž€LS¤‡Kð’ûcº_ï\x139"
  12 => b"Ž€L¨¶ôFü§pvà1À?~"
  13 => b"Ž€LîlâLö™Ï÷,&ÿ\x08±"
  14 => b"ÄÇM>¨NK¶ñÃh\x04Ø├gA"
  15 => b"ÄäMì┴×Gù½ôWÝ\x11ES²"
  16 => b"Žñ\x02\x08\x17\x00NP†o«ã\tvžt"
  17 => b"Žñ\x03\x05]ðH•†7¼o…Sþ\x05"
  18 => b"Žñ\x03/¡~M¨—Ó1a\x7FN`)"
  19 => b"Žñ\x03[N\x1DAË¼ú½¥r\x10äá"
  20 => b"Žñ\x1EzÃh@{’7Î4ÿ–Á-"
  21 => b"Žñ )XmN;·RÒö\x03À3c"
]

array:1 [▼
  0 => b"ÄÇEâ3ÎM¦ñ┌?╬³çÅC"
]

array:21 [▼
  0 => b"Ž€E6Ó\x19Jý°\x1Ak%‚®éí"
  2 => b"Ž€E¯{ÔJ›…\x03¨)L/òº"
  3 => b"Ž€Eç?ML%µ\x1EGUY\x128«"
  4 => b"Ž€F\x03\½JÚšbå.ª\x124ö"
  5 => b"Ž€F›Â…E\x03’ÇÄá]4Ÿ1"
  6 => b"Ž€F»JœEf˜\x1FYÌZ»óJ"
  7 => b"Ž€G›{CL%½¾\x07Â@Çû¤"
  8 => b"""
    ÄÇHVJ


    AÅÉïƒ ¶ÌÖj
    """
  9 => b"Ž€IS †I:ŽrÐ\x1Fç¤Û\x13"
  10 => b"Ž€K¹ë\eIc™ˆor6ÄIK"
  11 => b"Ž€LS¤‡Kð’ûcº_ï\x139"
  12 => b"Ž€L¨¶ôFü§pvà1À?~"
  13 => b"Ž€LîlâLö™Ï÷,&ÿ\x08±"
  14 => b"ÄÇM>¨NK¶ñÃh\x04Ø├gA"
  15 => b"ÄäMì┴×Gù½ôWÝ\x11ES²"
  16 => b"Žñ\x02\x08\x17\x00NP†o«ã\tvžt"
  17 => b"Žñ\x03\x05]ðH•†7¼o…Sþ\x05"
  18 => b"Žñ\x03/¡~M¨—Ó1a\x7FN`)"
  19 => b"Žñ\x03[N\x1DAË¼ú½¥r\x10äá"
  20 => b"Žñ\x1EzÃh@{’7Î4ÿ–Á-"
  21 => b"Žñ )XmN;·RÒö\x03À3c"
]

Category::whereIn('id', $parents)

passing last array in $parents makes the above exception

**Comment by padre** [comment] 2019-11-08 15:16
@mikebronner, this exception happens to me frequently :-(

My models uses \Ramsey\Uuid\Uuid too. An example:

`vsprintf(): Too few arguments {"userId":15,"exception":"[object] (ErrorException(code: 0): vsprintf(): Too few arguments at /var/app/current/vendor/genealabs/laravel-model-caching/src/CacheKey.php:233)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'vsprintf(): Too...', '/var/app/curren...', 233, Array)
#1 /var/app/current/vendor/genealabs/laravel-model-caching/src/CacheKey.php(233): vsprintf('%s%<\\x96\\xD3DN\\xB7\\x9C\\xE5'\\xF0\\xAB\\xE1...', Array)
#2 /var/app/current/vendor/genealabs/laravel-model-caching/src/CacheKey.php(197): GeneaLabs\\LaravelModelCaching\\CacheKey->getInAndNotInClauses(Array)
#3 [internal function]: GeneaLabs\\LaravelModelCaching\\CacheKey->GeneaLabs\\LaravelModelCaching\\{closure}(NULL, Array)
#4 /var/app/current/vendor/laravel/framework/src/Illuminate/Support/Collection.php(890): array_reduce(Array, Object(Closure), NULL)
#5 /var/app/current/vendor/genealabs/laravel-model-caching/src/CacheKey.php(201): Illuminate\\Support\\Collection->reduce(Object(Closure))
#6 /var/app/current/vendor/genealabs/laravel-model-caching/src/CacheKey.php(40): GeneaLabs\\LaravelModelCaching\\CacheKey->getWhereClauses()
#7 /var/app/current/vendor/genealabs/laravel-model-caching/src/Traits/Caching.php(161): GeneaLabs\\LaravelModelCaching\\CacheKey->make(Array, NULL, '-first')
#8 /var/app/current/vendor/genealabs/laravel-model-caching/src/Traits/Buildable.php(75): GeneaLabs\\LaravelModelCaching\\CachedBuilder->makeCacheKey(Array, NULL, '-first')
#9 /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(450): GeneaLabs\\LaravelModelCaching\\CachedBuilder->first(Array)
`

Thanks for the great library.

**Comment by padre** [comment] 2019-11-18 21:02
@mikebronner Sometimes the exception vsprintf(): Too few arguments and other times vsprintf(): Argument number must be greater than zero in CacheKey.php:233

It's to be used [binary uuid](https://github.com/michaeldyrynda/laravel-efficient-uuid)

I made the following fix and the problem has not recurred:

`protected function getInAndNotInClauses(array $where) : string
    {
        if (! in_array($where["type"], ["In", "NotIn", "InRaw"])) {
            return "";
        }

        $type = strtolower($where["type"]);
        $subquery = $this->getValuesFromWhere($where);
        $values = collect($this->query->bindings["where"][$this->currentBinding] ?? []);
        $this->currentBinding += count($where["values"]);
        
        if(!is_numeric($subquery) && !is_numeric(str_replace("_","",$subquery))){
            try{
                $subquery = \Ramsey\Uuid\Uuid::fromBytes($subquery);
                $values = $this->recursiveImplode([$subquery], "_");
                return "-{$where["column"]}_{$type}{$values}";
            }
            catch (\Exception $e){
                
            } 
        }
        
        $subquery = preg_replace('/\?(?=(?:[^"]*"[^"]*")*[^"]*\Z)/m', "_??_", $subquery);
        $subquery = collect(vsprintf(str_replace("_??_", "%s", $subquery), $values->toArray()));
        $values = $this->recursiveImplode($subquery->toArray(), "_");
        return "-{$where["column"]}_{$type}{$values}";
        
    }`

**Comment by mikebronner** [comment] 2019-12-22 18:58
@padre the UUID package you linked to should not be used as the primary key. However, I have added the code you recommended, as it does not break any test. Unfortunately the tests for this are very impractical. I would definitely appreciate a PR from you, if you have the time. Thanks!

**Comment by mikebronner** [comment] 2019-12-22 19:02
Closing this for now. Please check release 0.7.3 and let me know how it works for you.

**Closed by mikebronner** 2019-12-22 19:02 UTC
Labels: bug

**Comment by edtsz** [comment] 2020-05-29 02:24
Hello,
I'm getting trouble with vsprintf too and also using UUID as PK whatever the uuid was not an issue

```php
Document::select()
    ->with('author')
    ->whereIn('id', function ($query) use ($args) {
        return $query->from('comments')
            ->select('document_id')
            ->distinct()
            ->where('user_id', auth()->user()->getAuthIdentifier()) // deleting this line and works nice
            ->where('folder_id', $args['folder_id'])
            ->whereNull([
                'replaced_id',
                'archived_at',
                'deleted_at'
            ])
            ->orderBy('created_at', 'asc');
    })
    ->paginate($args['limit'], [], 'page', $args['page']);```

**Comment by edtsz** [comment] 2020-05-29 03:27
Hello,
I'm getting trouble with `vsprintf` too and also using UUID as PK whatever the uuid was not the issue

```php
Document::select()
    ->with('author')
    ->whereIn('id', function ($query) use ($args) {
        return $query->from('comments')
            ->select('document_id')
            ->distinct()
            ->where('user_id', auth()->user()->getAuthIdentifier()) // deleting this line and works nice
            ->where('folder_id', $args['folder_id'])
            ->whereNull([
                'replaced_id',
                'archived_at',
                'deleted_at'
            ]);
    })
    ->paginate($args['limit'], [], 'page', $args['page']);
```

Laravel: 5.8
Model Cache: 0.5.6 (PS.: I tried the most recent version and also didn't wokt)

Stacktrace:
```
ERROR: vsprintf(): Too few arguments at vendor/genealabs/laravel-model-caching/src/CacheKey.php:232
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'vsprintf(): Too...', '/home/edtsz/R...', 232, Array)
#1 vendor/genealabs/laravel-model-caching/src/CacheKey.php(232): vsprintf('select distinct...', Array)
#2 vendor/genealabs/laravel-model-caching/src/CacheKey.php(197): GeneaLabs\\LaravelModelCaching\\CacheKey->getInAndNotInClauses(Array)
#3 [internal function]: GeneaLabs\\LaravelModelCaching\\CacheKey->GeneaLabs\\LaravelModelCaching\\{closure}(NULL, Array)
#4 vendor/laravel/framework/src/Illuminate/Support/Collection.php(1512): array_reduce(Array, Object(Closure), NULL)
#5 vendor/genealabs/laravel-model-caching/src/CacheKey.php(201): Illuminate\\Support\\Collection->reduce(Object(Closure))
#6 vendor/genealabs/laravel-model-caching/src/CacheKey.php(40): GeneaLabs\\LaravelModelCaching\\CacheKey->getWhereClauses()
#7 vendor/genealabs/laravel-model-caching/src/Traits/Caching.php(161): GeneaLabs\\LaravelModelCaching\\CacheKey->make(Array, NULL, '-paginate_by_60...')
#8 vendor/genealabs/laravel-model-caching/src/Traits/Buildable.php(160): GeneaLabs\\LaravelModelCaching\\CachedBuilder->makeCacheKey(Array, NULL, '-paginate_by_60...')
#9 app/GraphQL/Queries/Document/DocumentsByFolderQuery.php(143): GeneaLabs\\LaravelModelCaching\\CachedBuilder->paginate(60, Array, 'page', 1)
"}
```

Digging into the code I realize that `$values` is receiving just one of the `where()` params at [this line](https://github.com/GeneaLabs/laravel-model-caching/blob/0.5.6/src/CacheKey.php#L230)
So I decide to make a few changes:

```php
// so I changed from                                vvvvvvvvvvvvvvvvvvvvvvv
// $values = collect($this->query->bindings["where"][$this->currentBinding] ?? []);
// to
   $values = collect(array_slice($this->query->bindings["where"], 1, substr_count($subquery, '?')) ?? []);
```
after that everything seems to be running well (yet)
ps.: slice starting from 1 because my query has 2 wheres and I don't know why there is a 0 in front off them.
the only thing I didn't like that much is the index name:
```txt
genealabs:laravel-model-caching:mysql:prod:documents:documents:appmodelsdocument_*-sandbox_=_0-id_in_select_distinct_`document_id`_from_`comments`_where_`user_id`_=_zzzzzzzzzzzzzzzzzzzzzzz_and_`folder_id`_=_xxxxxxxxxxxxxxxxxxxxxxxxxxxxx_and_`replaced_id`_is_null_and_`archived_at`_is_null_and_`deleted_at`_is_null-documents.deleted_at_null-mysql:prod:comments-comments.children-comments.children.user-comments.children.user.emails-comments.action-comments.events-comments.user-comments.user.emails-comments.user.organization-comments.user.organization.user-comments.link_orderBy_created_at_desc-paginate_by_60_page_1
```

**Comment by edtsz** [comment] 2020-05-29 03:39
Something weird happens here, my other environment `$this->query->bindings["where"]` is correct, with just 2 params.. and `$this->currentBinding` has 0 value.

**Comment by mikebronner** [comment] 2020-05-29 17:59
@edtsz You indicate you are running Laravel 5.8. The most recent version is only compatible with Laravel 7.x. You mentioned you tried the latest version of the package, did you try it with Laravel 7?

**Comment by edtsz** [comment] 2020-05-29 19:40
@mikebronner while testing I tried replacing `CacheKey.php` file by a new one. Everything works fine (except with more then one _where_). Laravel still 5.8

**Comment by mikebronner** [comment] 2020-05-29 19:43
@edtsz Sounds good ... sorry, we don't support older versions of this package. You're welcome to fork this project and make any fixes you need on your own branch for your own purposes.

**Comment by doiprojectcom** [comment] 2022-09-28 05:48
`$subquery = collect(**vsprintf**(str_replace("?", "%s", $subquery), $values->toArray()));`
replace to
`$subquery = collect(**vsprintf**(str_replace("?", "%%s", $subquery), $values->toArray()));`
