### ISSUE TITLE
Inavalidation Problems since last version

### ISSUE THREAD

**Issue by jetwes** [GeneaLabs/laravel-model-caching#91] opened 2018-02-28 10:16 UTC
I just updated to the latest version and now i have strange errors - maybe something todo with invalidation. (or not invalidating)

Example: 
In my SalesController i prepare to add another product to the basket.
`
$saleItem = SaleItem::where('id','=',$request->get('id'))->first();
$product = Product::where('id',$request->get('product_id'))->first();
$saleItem->product_id = $product->id;
`
Now sometimes - mostly when more than one product is in the basket i get this error:
`Property [id] does not exist on this collection instance.`  (Regarding the line $product->id)
If i disable the cache everything is ok. Before i updated to the current version everything was fine, too.

What could be the problem over here. I have the same error on different Controllers - not only regarding products.. I disabled the whole cache now - because i'm getting many errors like these...

PHP 7.1
Laravel 5.5
latest package version

**Comment by mikebronner** [comment] 2018-02-28 12:59
Thanks, @jetwes , I will look into this. Have you been able to see any kind of pattern that might be causing this? Are you using the cache cool down option?

**Comment by jetwes** [comment] 2018-02-28 13:12
No, i'm not using the cool down option. I cant'see a pattern at the moment.
Another example: 
`if ($user->last_shop_id != null) {
                    $shop = Shop::where('id', '=', $user->last_shop_id)->first();
                } else {
                    $shop = Shop::where('id', '=', $user->main_shop_id)->first();
                }
                //$user->setShop(['id' => $shops->id,'name' => $shops->shortname]);
                $user->setShop(['id' => $shop->id, 'name' => $shop->shortname]);`

I get an `Trying to get property of non-object` error on the last line - it seems that $shop isn't fetched correctly. If i disable the cache everything is fine. It's on my login controller - within the setShop method i set a default shop for my session. I don't cache the user model. If i disabling the cache on the shop model - everything is ok. I was on version 0.2.23 before updating this morning. The issues started right after the update to the latest version.

**Comment by jetwes** [comment] 2018-02-28 13:24
Another example:
`$shops = Shop::where('active',1)->where('shortname','!=','Zentrale')->where('micro_region',Shop::where('id',Auth::user()->main_shop_id)->first()->micro_region)->orderBy('shortname','ASC')`

Error: `Exception · Property [micro_region] does not exist on this collection instance.`

The errors don't accur on every requests - but a couple of times in a minute...

**Comment by mikebronner** [comment] 2018-02-28 14:07
@jetwes thanks again for the details. It almost sounds like different users are overriding the query cache in different circumstances, which if true, means that some keys are not granular enough, and even though you specified `first()1st it's actually returning the collection.

**Comment by mikebronner** [comment] 2018-02-28 14:51
@jetwes I had another thought. If you could see if you can get this error to happen again in your dev environment, would you be able to look at the collection that it errors on, and see what query created that collection? If so, that would be the smoking gun we need to identify the source of the problem. In the mean while I am writing a few more tests to cover some scenarios I can think of.

**Comment by jetwes** [comment] 2018-02-28 17:53
ok, i'll have a look at it, later

**Comment by jetwes** [comment] 2018-02-28 18:56
Ok - seems that the mess is on my side. I have a couple of queries ending ->get()[0]; instead of using ->first();
All this queries fail. When i change them, flush the cache - than they are working.
Sorry for confusing. I will monitor this further...

But there's a strange thing. php artisan modelCache:flush --model=Portal\\Models\\Sale
I tried `php artisan modelCache:flush --model=Portal\\Models\\Shop` to flush the cache model and i get the error `'Portal\Models\Sale' is not an instance of CachedModel.`
The Model uses the trait Cachable...

**Comment by mikebronner** [comment] 2018-02-28 18:57
Hi @jetwes, awesome, thanks for researching this further.

Try the following on the commandline: `php artisan modelCache:flush --model=\\Portal\\Models\\Shop` (not the leading slash). Let me know if that doesn't work.

**Comment by mikebronner** [comment] 2018-02-28 19:15
Thanks for checking. I will look into why models can't be flushed from the command-line and see if there is an edge-case.

The way data is stored in the cache changed, but it shouldn't affect being able to access an index on a collection (since get should always return a collection, which is stored in cache). Could you provide me with a full query that you are trying to run, ending in `[0]`. I will use that to write a test to see what happens.

In the mean time, I would highly recommend using a dedicated cache store for model-caching, if you haven't already done so. You can then flush the cache for models without affecting your normal cache, by simply omitting the model options on the command-line: `php artisan modelCache:flush`. I do still need to document that better on the readme -- both how to flush the complete cache, as well as set up a dedicated cache.

**Comment by jetwes** [comment] 2018-02-28 19:53
i'm using redis in a seperate database.

An example Query: 
`$saleItem = SaleItem::where('id','=',Request::input('id'))->get()[0];`

I already refactored most of the old queries to first() - i will monitor this in the next days..

**Comment by mikebronner** [comment] 2018-02-28 19:54
Thanks! I will try to make a test case this evening and report back

**Comment by mikebronner** [comment] 2018-02-28 23:48
Hi @jetwes, I tried to replicate the problem, but was unable to get a failure out of it. See my unit test here (https://github.com/GeneaLabs/laravel-model-caching/commit/44fccfc99cd72a76b8c629d826079b781bc9d1bb). If you can think of anything or provide steps to reproduce, or even a unit test, that would be awesome!

**Comment by mikebronner** [comment] 2018-02-28 23:49
Also, you could simplify your query, by using `find()`, perhaps like so:
```php
$saleItem = SaleItem::find(Request::input('id'));
```

**Comment by mikebronner** [comment] 2018-02-28 23:54
Also, I covered the process I went through here, let me know if I missed something: https://t.co/CHKiHkfYGz

I would probably suggest opening a new issue if you find a problem, as the original issue on this one has been resolved, and we're working on secondary things now. :)

**Comment by mikebronner** [comment] 2018-03-01 00:34
I am able to replicate the flushing issue ... working on that separate from this issue

**Comment by mikebronner** [comment] 2018-03-01 01:37
Fix for model flush command will be in the next release in a few minutes. :)

**Comment by jetwes** [comment] 2018-03-01 06:34
Thank you!

**Comment by jetwes** [comment] 2018-03-01 10:15
The problem still persists. Changing to first() fixed the error message itself - but the value is still not fetched from the cache.
![image](https://user-images.githubusercontent.com/1346373/36839031-1a7f9060-1d41-11e8-87d4-01fe59ba1f91.png)
In this example i display a list of users. The query is
`$users = User::with('role')->with('shop')->with('user_salaries')->get();`
As you can see in the pitcture the field under "Bonn-Duisdorf" is empty . Thats wrong - when i disable the cache i see the correct value "Münster-Hiltrup".

The view for this looks like `{{ $user->main_shop($user->main_shop_id)->shortname }}`
Method main_shop in my user model:
` public function main_shop($id)
    {
        return Shop::where('id', '=', $id)->first();
    }`

**Comment by mikebronner** [comment] 2018-03-01 13:54
Is Shop also using Cachable?  In your view, can dump out the user I'd in the loop, before you did play the main_shop? Could you post a demo repo with just the view, route, and controller needed to get this specific page to work? That way I could try to replicate the problem. I suspect the issue lies somewhere other than in the query itself.

**Comment by jetwes** [comment] 2018-03-01 16:23
i dumped out the user id - it's the correct user_id (the other list entries are correct - so no surprise)
![image](https://user-images.githubusercontent.com/1346373/36855938-1597ac70-1d75-11e8-9a1b-3ff1ff2fdfe3.png)
Yes, Shop is cachable.
I try to post a demo repo .

**Comment by jetwes** [comment] 2018-03-01 16:24
by the way - the user is not cachable.

**Comment by jetwes** [comment] 2018-03-02 13:06
i posted it to a repo - you got an invite link. Its straighforwarded - i uploaded vendor, too. so just clone it and you are ready. a sql is inside the migrations folder for quick generetion of the db tables.
I deleted all other stuff, like auth etc.

**Comment by mikebronner** [comment] 2018-03-03 02:28
Got the invite, thanks! Will take a look at it tomorrow :)

**Comment by mikebronner** [comment] 2018-03-03 15:09
@jetwes I started installing the repo, but it appears the migration folder is missing. Could you add that for me? :) Thanks!

**Comment by jetwes** [comment] 2018-03-05 10:54
oh sorry - i'm looking for it this evening - i was sick the last couple of days - sorry for the delay

**Comment by mikebronner** [comment] 2018-03-05 13:24
Hope you feel better - gute Besserung!

**Comment by jetwes** [comment] 2018-03-07 07:56
thank you mike - danke schön ;)
Just uploaded the folder

**Comment by mikebronner** [comment] 2018-03-11 03:04
@jetwes I fixed an issue with `first()` not invalidating, could you try again with the latest version?

**Comment by jetwes** [comment] 2018-03-12 08:11
@mikebronner it seems to work as expected! I will have a look on the logs today - but it's looking good at the moment!

**Closed** 2018-03-12 14:03 UTC
Labels: follow-up required
