### ISSUE TITLE
Not getting all model attributes on query 

### ISSUE THREAD

**Issue by jetwes** [GeneaLabs/laravel-model-caching#107] opened 2018-03-29 07:35 UTC
Hi MIke,

it's me again with a strange behaviour ;)

In a controller i am doing this:

```
 $shop = Shop::where('id', '=', $request->get('shop_id'))->first();
 dd($shop);
```
Unfortunately i'm only getting one attribute back - not all like intended.
If i disable the cache i'm getting all attributes.
```
 $shop = Shop::where('id', '=', $request->get('shop_id'))->disableModelCaching()->first();
 dd($shop);
```
See the attached pictures.

Any clue why this is happening?

Thx
Jens
<img width="370" alt="shop_enabled_cache" src="https://user-images.githubusercontent.com/1346373/38075984-7a0b68f2-3334-11e8-81cf-ccd0edf4c72a.PNG">
<img width="373" alt="shop_disabled_cache" src="https://user-images.githubusercontent.com/1346373/38075985-7a270864-3334-11e8-99a6-c5853a9152e8.PNG">

**Comment by mikebronner** [comment] 2018-03-29 15:57
Hi @jetwes thanks for reporting this :) I will take a look, it might take some time though, as I am travelling, and won't be back at my office until next week.

**Comment by jetwes** [comment] 2018-04-02 09:32
no worries

**Comment by shenjiayu** [comment] 2018-05-02 09:54
@jetwes Have you resolved this issue? if not, could you please provide more information?

**Comment by jetwes** [comment] 2018-05-03 09:47
No i didn't and i really don't know what kind of informations could help - the problem is pretty clear - i  think..

**Comment by mikebronner** [comment] 2018-05-03 15:38
@jetwes Sorry for the delays, I'm currently swamped with work and deadlines.

**Comment by shenjiayu** [comment] 2018-05-04 01:26
@jetwes Probably provide us with the minimal runnable code to reproduce this issue?

**Comment by mikebronner** [comment] 2018-05-04 01:29
@shenjiayu I have what I need from what @jetwes already reported. Also, please don't represent yourself as one of the maintainers by saying "us" and asking people to submit more information.

**Comment by shenjiayu** [comment] 2018-05-04 01:31
@mikebronner Noted..Just wanted to see if I can help out since I couldn't simply reproduce it on my local. : )

**Comment by mikebronner** [comment] 2018-05-04 01:33
@shenjiayu Gotcha, thanks. In those cases it would probably help to provide your eloquent query that shows it working. :)

**Comment by jetwes** [comment] 2018-05-04 07:05
@mikebronner no worries!

**Comment by mikebronner** [comment] 2018-05-12 19:46
@jetwes I have set up a test for this, but have not been able to reproduce it. Can you clear your cache, and make sure you have the latest version of the plugin and try again? Thanks!

```php
    public function testFirstReturnsAllAttributesForModel()
    {
        $author = (new Author)->where("id", "=", 1)->first();
        $uncachedAuthor = (new UncachedAuthor)->where("id", "=", 1)->first();

        $this->assertEquals($author->id, $uncachedAuthor->id);
        $this->assertEquals($author->created_at, $uncachedAuthor->created_at);
        $this->assertEquals($author->updated_at, $uncachedAuthor->updated_at);
        $this->assertEquals($author->email, $uncachedAuthor->email);
        $this->assertEquals($author->name, $uncachedAuthor->name);
    }
```

**Comment by mikebronner** [comment] 2018-05-19 00:50
@jetwes I'll close this for now, but if you do still have this same issue, please re-open. Thanks!

**Closed by mikebronner** 2018-05-19 00:50 UTC
Labels: Unconfirmed Bug, follow-up required
