### ISSUE TITLE
all()/get() with only 1 entry returns the model, not a collection

### ISSUE THREAD

**Issue by bastian-schur** [GeneaLabs/laravel-model-caching#82] opened 2018-02-19 14:47 UTC
Laravel 5.5, laravel-model-caching: 0.2.31

If i use caching with my models and there is only one result on calling all()/get() i receive the model, not a collection. This is a different handling to laravel!

**Comment by mikebronner** [comment] 2018-02-19 15:33
@bastian-schur Thanks for reporting. I will look into that ASAP. (Might have to wait until later today, but will be today for sure.)

**Comment by mikebronner** [comment] 2018-02-19 16:32
@bastian-schur I have not been able to replicate this. I tried the following query on different models, and they returned multiple results:
```php
Model::all()->count();
```

Could you clear your cache and try again? Are you running a query on the same model before this one that returns only one result? (I'm wondering if perhaps the package is not creating the correct cache keys, or re-using on old cache key when running `all()`.)

If you can provide some more information, that would help a lot! :)

**Comment by bastian-schur** [comment] 2018-02-19 16:53
@mikebronner This problem only occurs if in your database table is only ONE(!) entry! In this case you get the same result like find or first - the requestet model itself. But all or get should return everytime a collection, also there is only one item.
I tryed this with the fallowing steps:
1) Enable Caching, run dd(Model::all()) -> You receive the Model
2) Disable Caching, run dd(Model::all()) -> You receive a collection with one Model

**Comment by mikebronner** [comment] 2018-02-19 17:04
Ah! Thank you for expanding on the issue. I will check that.

**Comment by mikebronner** [comment] 2018-02-20 02:28
Hi @bastian-schur, I was unable to recreate the issue. I implemented an integration test with only one record in the database, and it consistently returns a collection as intended. Can you provide a test repo using a fresh laravel install that reproduces this issue? Thanks!

**Comment by bastian-schur** [comment] 2018-02-20 08:19
@mikebronner I will try it soon, but today i think i will get no time for this. In a short test i tryed it with extending my model directly from eloquent/model, so the modifications in my basemodel will have no influence. I also tryed it with laravel 5.6 but it takes no effect: same result.

**Comment by mikebronner** [comment] 2018-02-22 04:20
Hi @bastian-schur, could you try again using release 0.2.34? I have gone through and done some refactoring and quite a bit of cleanup. Please let me know how that works for you. :)

**Comment by bastian-schur** [comment] 2018-02-22 14:03
@mikebronner thanks for your feedback. Unfortunately, there is no change with the problem.
I look forward to analyze the problem with a fresh laravel installation soon.

**Comment by mikebronner** [comment] 2018-02-22 14:32
@bastian-schur Thank you, please let me know your results, as I have been unable to replicate the issue so far.

**Comment by mikebronner** [comment] 2018-03-01 00:23
@bastian-schur closing this for now, please let me know if you continue to have this problem.

**Closed by mikebronner** 2018-03-01 00:23 UTC
Labels: follow-up required

**Comment by bastian-schur** [comment] 2018-03-09 11:31
@mikebronner: I just wanted to say that the problem in the current version 0.2.47 no longer occurs. Apparently, various changes have eliminated the problem. 
Thanks for the active development!

**Comment by mikebronner** [comment] 2018-03-09 16:18
Thanks for following up! :) Glad its working as intended. :)
