### ISSUE TITLE
Please add support for laravel 5.7

### ISSUE THREAD

**Issue by Tachii** [GeneaLabs/laravel-model-caching#164] opened 2018-09-07 10:23 UTC
Could you please update your composer.json to match laravel 5.7? Currently its not compatible

**Comment by mikebronner** [comment] 2018-09-07 14:39
Duplicate of #161

**Closed by mikebronner** 2018-09-07 14:39 UTC

**Comment by mikebronner** [comment] 2018-09-10 23:41
@Tachii Laravel 5.7 support is now available in version 0.3.0
