### ISSUE TITLE
Cachable conflict

### ISSUE THREAD

**Issue by wilbur-oo** [GeneaLabs/laravel-model-caching#363] opened 2020-07-22 02:36 UTC
![image](https://user-images.githubusercontent.com/7148309/88127792-2113bb00-cc07-11ea-858b-fd4c196930a1.png)
![image](https://user-images.githubusercontent.com/7148309/88127806-283ac900-cc07-11ea-87cd-03330459efaf.png)

**Comment by mikebronner** [comment] 2020-07-22 02:45
Duplicate of #361

**Closed by mikebronner** 2020-07-22 02:45 UTC
