### ISSUE TITLE
belongsToMany : updateExistingPivot does not update data 

### ISSUE THREAD

**Issue by AEK-BKF** [GeneaLabs/laravel-model-caching#118] opened 2018-04-22 19:42 UTC
# Issue
belongsToMany : updateExistingPivot does not update data 

## Environment
Laravel Version: *5.6.**
Laravel Model Caching Package Version: ^0.2.52*
PHP Version: *7.2.4*
Operating System & Version: *Ubuntu 16.04*

## Stack Trace
```
When update :
` $specyear->userresults()->updateExistingPivot($userID, ['admitted' => true]);`

And I retrieve like this :

`{{$specyear->userresults()->wherePivot('admitted',true)->count()}}`

Then the result is not what I expect !
```

**Comment by mikebronner** [comment] 2018-04-22 21:15
Thanks for the report! I will look into this as soon as possible. Unfortunately I haven't had much time recently to address outstanding issue. :(

**Comment by AEK-BKF** [comment] 2018-04-22 21:24
Yap ! You're right !
Thank you so much :)))

**Comment by mikebronner** [comment] 2018-04-22 21:28
let's keep this open until the issue is fixed :)

**Comment by mikebronner** [comment] 2018-05-06 18:52
I have not been able to replicate the issue. Using the following test, I get the expected results:
```php
        $book = (new Book)
            ->with("stores")
            ->whereHas("stores")
            ->first();
        $book->stores()
            ->updateExistingPivot(
                $book->stores->first()->id,
                ["test" => "value"]
            );
        $booksWithUpdatedPivot = (new Book)
            ->with("stores")
            ->whereHas("stores")
            ->first()
            ->stores()
            ->wherePivot("test", "value")
            ->count();

        dd("test", $booksWithUpdatedPivot);
```

**Comment by mikebronner** [comment] 2018-05-19 00:54
@AEK-BKF I'll close this for now, but please re-open if you are still having this issue.

**Closed by mikebronner** 2018-05-19 00:54 UTC
Labels: Unconfirmed Bug, follow-up required
