### ISSUE TITLE
Model caching doesn't handle Query\Expression objects as columns

### ISSUE THREAD

**Issue by ChenAlon** [GeneaLabs/laravel-model-caching#146] opened 2018-07-03 22:59 UTC
**Describe the bug**
When passing DB::raw() in the Builder select function, the cache does not consider these columns in the cache key which results in a wrong cache.
When passing DB::raw() to the select function it is resolved as a Query\Expression object.
As far as I can see, the issue is in the function  ```\GeneaLabs\LaravelModelCaching\CacheKey::getQueryColumns``` which doesn't handle this case.

I did a quick test and made the following change, it works as expected.
```php
    protected function getQueryColumns(array $columns) : string
    {
        if ($columns === ["*"] || $columns === []) {
            if (\is_array($this->query->columns)) {
                $columns = $this->query->columns;
            } else {
                return "";
            }
        }

        return "_" . str_replace(' ', '_', implode("_", $columns));
    }
```
(It can be implemented in a better way though).

**Eloquent Query**
```php
        $select_array = [
            DB::raw(_GROUP_COLUMN_),
            DB::raw(AVG(_AGGR_COLUMN_) AS _ALIAS_)
        ];

        $query = self::select($select_array)
            ->whereBetween(_DATE_COLUMN_, [$from_date, $to_date]);

        $query->groupBy(_GROUP_COLUMN_)
            ->orderBy(_GROUP_COLUMN_);

        return $query->get()->toArray();
```

**Environment**
 - PHP: 7.1.18
 - OS: macOS High Sierra 10.13.5 (Using Laravel Valet 2.0)
 - Laravel: 5.5.18
 - Model Caching: 0.2.63

**Additional context**
A screenshot to make it more clear:
![laravel-model-caching src cachekey](https://user-images.githubusercontent.com/4798088/42247785-f2551582-7f2a-11e8-891e-167a156668bb.jpg)

**Comment by mikebronner** [comment] 2018-07-11 14:10
Thanks for posting this issue. I will look into it as soon as I can. :)

**Comment by mikebronner** [comment] 2018-07-26 01:53
@ChenAlon I am unable to reproduce this issue with the eloquent query you provided in the example. I created an integration test, but it passes. Could you please test again using version 0.2.64 or greater? Thanks!

**Comment by mikebronner** [comment] 2018-08-04 13:03
Closing for now. Please re-open with a different eloquent query that also has this problem if this continues to occur.

**Closed by mikebronner** 2018-08-04 13:03 UTC
Labels: Unconfirmed Bug, follow-up required
